package streamanalytics

// Copyright (c) Microsoft and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

// ClusterProvisioningState enumerates the values for cluster provisioning state.
type ClusterProvisioningState string

const (
	// Canceled The cluster provisioning was canceled.
	Canceled ClusterProvisioningState = "Canceled"
	// Failed The cluster provisioning failed.
	Failed ClusterProvisioningState = "Failed"
	// InProgress The cluster provisioning was inprogress.
	InProgress ClusterProvisioningState = "InProgress"
	// Succeeded The cluster provisioning succeeded.
	Succeeded ClusterProvisioningState = "Succeeded"
)

// PossibleClusterProvisioningStateValues returns an array of possible values for the ClusterProvisioningState const type.
func PossibleClusterProvisioningStateValues() []ClusterProvisioningState {
	return []ClusterProvisioningState{Canceled, Failed, InProgress, Succeeded}
}

// ClusterSkuName enumerates the values for cluster sku name.
type ClusterSkuName string

const (
	// Default The default SKU.
	Default ClusterSkuName = "Default"
)

// PossibleClusterSkuNameValues returns an array of possible values for the ClusterSkuName const type.
func PossibleClusterSkuNameValues() []ClusterSkuName {
	return []ClusterSkuName{Default}
}

// JobState enumerates the values for job state.
type JobState string

const (
	// JobStateCreated The job is currently in the Created state.
	JobStateCreated JobState = "Created"
	// JobStateDegraded The job is currently in the Degraded state.
	JobStateDegraded JobState = "Degraded"
	// JobStateDeleting The job is currently in the Deleting state.
	JobStateDeleting JobState = "Deleting"
	// JobStateFailed The job is currently in the Failed state.
	JobStateFailed JobState = "Failed"
	// JobStateRestarting The job is currently in the Restarting state.
	JobStateRestarting JobState = "Restarting"
	// JobStateRunning The job is currently in the Running state.
	JobStateRunning JobState = "Running"
	// JobStateScaling The job is currently in the Scaling state.
	JobStateScaling JobState = "Scaling"
	// JobStateStarting The job is currently in the Starting state.
	JobStateStarting JobState = "Starting"
	// JobStateStopped The job is currently in the Stopped state.
	JobStateStopped JobState = "Stopped"
	// JobStateStopping The job is currently in the Stopping state.
	JobStateStopping JobState = "Stopping"
)

// PossibleJobStateValues returns an array of possible values for the JobState const type.
func PossibleJobStateValues() []JobState {
	return []JobState{JobStateCreated, JobStateDegraded, JobStateDeleting, JobStateFailed, JobStateRestarting, JobStateRunning, JobStateScaling, JobStateStarting, JobStateStopped, JobStateStopping}
}
