package anybuild

// Copyright (c) Microsoft and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

        // AgentsMode enumerates the values for agents mode.
    type AgentsMode string

    const (
                // Deflated ...
        Deflated AgentsMode = "Deflated"
                // Inflated ...
        Inflated AgentsMode = "Inflated"
            )
    // PossibleAgentsModeValues returns an array of possible values for the AgentsMode const type.
    func PossibleAgentsModeValues() []AgentsMode {
        return []AgentsMode{Deflated,Inflated}
    }

        // DayOfWeek enumerates the values for day of week.
    type DayOfWeek string

    const (
                // Friday ...
        Friday DayOfWeek = "Friday"
                // Monday ...
        Monday DayOfWeek = "Monday"
                // Saturday ...
        Saturday DayOfWeek = "Saturday"
                // Sunday ...
        Sunday DayOfWeek = "Sunday"
                // Thursday ...
        Thursday DayOfWeek = "Thursday"
                // Tuesday ...
        Tuesday DayOfWeek = "Tuesday"
                // Wednesday ...
        Wednesday DayOfWeek = "Wednesday"
            )
    // PossibleDayOfWeekValues returns an array of possible values for the DayOfWeek const type.
    func PossibleDayOfWeekValues() []DayOfWeek {
        return []DayOfWeek{Friday,Monday,Saturday,Sunday,Thursday,Tuesday,Wednesday}
    }

        // ProvisioningState enumerates the values for provisioning state.
    type ProvisioningState string

    const (
                // Canceled ...
        Canceled ProvisioningState = "Canceled"
                // Creating ...
        Creating ProvisioningState = "Creating"
                // Deflating ...
        Deflating ProvisioningState = "Deflating"
                // Deleting ...
        Deleting ProvisioningState = "Deleting"
                // Failed ...
        Failed ProvisioningState = "Failed"
                // Succeeded ...
        Succeeded ProvisioningState = "Succeeded"
                // Updating ...
        Updating ProvisioningState = "Updating"
            )
    // PossibleProvisioningStateValues returns an array of possible values for the ProvisioningState const type.
    func PossibleProvisioningStateValues() []ProvisioningState {
        return []ProvisioningState{Canceled,Creating,Deflating,Deleting,Failed,Succeeded,Updating}
    }

