package datacollaboration

// Copyright (c) Microsoft and contributors.  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
	"context"
	"github.com/Azure/go-autorest/autorest"
	"github.com/Azure/go-autorest/autorest/azure"
	"github.com/Azure/go-autorest/autorest/validation"
	"github.com/Azure/go-autorest/tracing"
	"net/http"
)

// ScriptReferencesClient is the creates a Microsoft.DataCollaboration management client.
type ScriptReferencesClient struct {
	BaseClient
}

// NewScriptReferencesClient creates an instance of the ScriptReferencesClient client.
func NewScriptReferencesClient(subscriptionID string) ScriptReferencesClient {
	return NewScriptReferencesClientWithBaseURI(DefaultBaseURI, subscriptionID)
}

// NewScriptReferencesClientWithBaseURI creates an instance of the ScriptReferencesClient client using a custom
// endpoint.  Use this when interacting with an Azure cloud that uses a non-standard base URI (sovereign clouds, Azure
// stack).
func NewScriptReferencesClientWithBaseURI(baseURI string, subscriptionID string) ScriptReferencesClient {
	return ScriptReferencesClient{NewWithBaseURI(baseURI, subscriptionID)}
}

// CreateOrUpdate create or update a ScriptReference in a Proposal
// Parameters:
// resourceGroupName - the resource group name.
// workspaceName - the name of the workspace.
// proposalName - the name of the proposal.
// referenceName - the name of the reference.
// scriptReference - the new script reference information.
func (client ScriptReferencesClient) CreateOrUpdate(ctx context.Context, resourceGroupName string, workspaceName string, proposalName string, referenceName string, scriptReference ScriptReference) (result ScriptReference, err error) {
	if tracing.IsEnabled() {
		ctx = tracing.StartSpan(ctx, fqdn+"/ScriptReferencesClient.CreateOrUpdate")
		defer func() {
			sc := -1
			if result.Response.Response != nil {
				sc = result.Response.Response.StatusCode
			}
			tracing.EndSpan(ctx, sc, err)
		}()
	}
	if err := validation.Validate([]validation.Validation{
		{TargetValue: scriptReference,
			Constraints: []validation.Constraint{{Target: "scriptReference.ScriptReferenceProperties", Name: validation.Null, Rule: true,
				Chain: []validation.Constraint{{Target: "scriptReference.ScriptReferenceProperties.Revision", Name: validation.Null, Rule: true, Chain: nil},
					{Target: "scriptReference.ScriptReferenceProperties.ScriptID", Name: validation.Null, Rule: true, Chain: nil},
				}}}}}); err != nil {
		return result, validation.NewError("datacollaboration.ScriptReferencesClient", "CreateOrUpdate", err.Error())
	}

	req, err := client.CreateOrUpdatePreparer(ctx, resourceGroupName, workspaceName, proposalName, referenceName, scriptReference)
	if err != nil {
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "CreateOrUpdate", nil, "Failure preparing request")
		return
	}

	resp, err := client.CreateOrUpdateSender(req)
	if err != nil {
		result.Response = autorest.Response{Response: resp}
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "CreateOrUpdate", resp, "Failure sending request")
		return
	}

	result, err = client.CreateOrUpdateResponder(resp)
	if err != nil {
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "CreateOrUpdate", resp, "Failure responding to request")
	}

	return
}

// CreateOrUpdatePreparer prepares the CreateOrUpdate request.
func (client ScriptReferencesClient) CreateOrUpdatePreparer(ctx context.Context, resourceGroupName string, workspaceName string, proposalName string, referenceName string, scriptReference ScriptReference) (*http.Request, error) {
	pathParameters := map[string]interface{}{
		"proposalName":      autorest.Encode("path", proposalName),
		"referenceName":     autorest.Encode("path", referenceName),
		"resourceGroupName": autorest.Encode("path", resourceGroupName),
		"subscriptionId":    autorest.Encode("path", client.SubscriptionID),
		"workspaceName":     autorest.Encode("path", workspaceName),
	}

	const APIVersion = "2020-05-04-preview"
	queryParameters := map[string]interface{}{
		"api-version": APIVersion,
	}

	preparer := autorest.CreatePreparer(
		autorest.AsContentType("application/json; charset=utf-8"),
		autorest.AsPut(),
		autorest.WithBaseURL(client.BaseURI),
		autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataCollaboration/workspaces/{workspaceName}/proposals/{proposalName}/scriptReferences/{referenceName}", pathParameters),
		autorest.WithJSON(scriptReference),
		autorest.WithQueryParameters(queryParameters))
	return preparer.Prepare((&http.Request{}).WithContext(ctx))
}

// CreateOrUpdateSender sends the CreateOrUpdate request. The method will close the
// http.Response Body if it receives an error.
func (client ScriptReferencesClient) CreateOrUpdateSender(req *http.Request) (*http.Response, error) {
	return client.Send(req, azure.DoRetryWithRegistration(client.Client))
}

// CreateOrUpdateResponder handles the response to the CreateOrUpdate request. The method always
// closes the http.Response Body.
func (client ScriptReferencesClient) CreateOrUpdateResponder(resp *http.Response) (result ScriptReference, err error) {
	err = autorest.Respond(
		resp,
		azure.WithErrorUnlessStatusCode(http.StatusOK, http.StatusCreated),
		autorest.ByUnmarshallingJSON(&result),
		autorest.ByClosing())
	result.Response = autorest.Response{Response: resp}
	return
}

// Delete delete a ScriptReference in a Proposal
// Parameters:
// resourceGroupName - the resource group name.
// workspaceName - the name of the workspace.
// proposalName - the name of the proposal.
// referenceName - the name of the reference.
func (client ScriptReferencesClient) Delete(ctx context.Context, resourceGroupName string, workspaceName string, proposalName string, referenceName string) (result ScriptReferencesDeleteFuture, err error) {
	if tracing.IsEnabled() {
		ctx = tracing.StartSpan(ctx, fqdn+"/ScriptReferencesClient.Delete")
		defer func() {
			sc := -1
			if result.Response() != nil {
				sc = result.Response().StatusCode
			}
			tracing.EndSpan(ctx, sc, err)
		}()
	}
	req, err := client.DeletePreparer(ctx, resourceGroupName, workspaceName, proposalName, referenceName)
	if err != nil {
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "Delete", nil, "Failure preparing request")
		return
	}

	result, err = client.DeleteSender(req)
	if err != nil {
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "Delete", result.Response(), "Failure sending request")
		return
	}

	return
}

// DeletePreparer prepares the Delete request.
func (client ScriptReferencesClient) DeletePreparer(ctx context.Context, resourceGroupName string, workspaceName string, proposalName string, referenceName string) (*http.Request, error) {
	pathParameters := map[string]interface{}{
		"proposalName":      autorest.Encode("path", proposalName),
		"referenceName":     autorest.Encode("path", referenceName),
		"resourceGroupName": autorest.Encode("path", resourceGroupName),
		"subscriptionId":    autorest.Encode("path", client.SubscriptionID),
		"workspaceName":     autorest.Encode("path", workspaceName),
	}

	const APIVersion = "2020-05-04-preview"
	queryParameters := map[string]interface{}{
		"api-version": APIVersion,
	}

	preparer := autorest.CreatePreparer(
		autorest.AsDelete(),
		autorest.WithBaseURL(client.BaseURI),
		autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataCollaboration/workspaces/{workspaceName}/proposals/{proposalName}/scriptReferences/{referenceName}", pathParameters),
		autorest.WithQueryParameters(queryParameters))
	return preparer.Prepare((&http.Request{}).WithContext(ctx))
}

// DeleteSender sends the Delete request. The method will close the
// http.Response Body if it receives an error.
func (client ScriptReferencesClient) DeleteSender(req *http.Request) (future ScriptReferencesDeleteFuture, err error) {
	var resp *http.Response
	resp, err = client.Send(req, azure.DoRetryWithRegistration(client.Client))
	if err != nil {
		return
	}
	future.Future, err = azure.NewFutureFromResponse(resp)
	return
}

// DeleteResponder handles the response to the Delete request. The method always
// closes the http.Response Body.
func (client ScriptReferencesClient) DeleteResponder(resp *http.Response) (result OperationResponse, err error) {
	err = autorest.Respond(
		resp,
		azure.WithErrorUnlessStatusCode(http.StatusOK, http.StatusAccepted, http.StatusNoContent),
		autorest.ByUnmarshallingJSON(&result),
		autorest.ByClosing())
	result.Response = autorest.Response{Response: resp}
	return
}

// Get get a ScriptReference in a Proposal
// Parameters:
// resourceGroupName - the resource group name.
// workspaceName - the name of the workspace.
// proposalName - the name of the proposal.
// referenceName - the name of the reference.
func (client ScriptReferencesClient) Get(ctx context.Context, resourceGroupName string, workspaceName string, proposalName string, referenceName string) (result ScriptReference, err error) {
	if tracing.IsEnabled() {
		ctx = tracing.StartSpan(ctx, fqdn+"/ScriptReferencesClient.Get")
		defer func() {
			sc := -1
			if result.Response.Response != nil {
				sc = result.Response.Response.StatusCode
			}
			tracing.EndSpan(ctx, sc, err)
		}()
	}
	req, err := client.GetPreparer(ctx, resourceGroupName, workspaceName, proposalName, referenceName)
	if err != nil {
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "Get", nil, "Failure preparing request")
		return
	}

	resp, err := client.GetSender(req)
	if err != nil {
		result.Response = autorest.Response{Response: resp}
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "Get", resp, "Failure sending request")
		return
	}

	result, err = client.GetResponder(resp)
	if err != nil {
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "Get", resp, "Failure responding to request")
	}

	return
}

// GetPreparer prepares the Get request.
func (client ScriptReferencesClient) GetPreparer(ctx context.Context, resourceGroupName string, workspaceName string, proposalName string, referenceName string) (*http.Request, error) {
	pathParameters := map[string]interface{}{
		"proposalName":      autorest.Encode("path", proposalName),
		"referenceName":     autorest.Encode("path", referenceName),
		"resourceGroupName": autorest.Encode("path", resourceGroupName),
		"subscriptionId":    autorest.Encode("path", client.SubscriptionID),
		"workspaceName":     autorest.Encode("path", workspaceName),
	}

	const APIVersion = "2020-05-04-preview"
	queryParameters := map[string]interface{}{
		"api-version": APIVersion,
	}

	preparer := autorest.CreatePreparer(
		autorest.AsGet(),
		autorest.WithBaseURL(client.BaseURI),
		autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataCollaboration/workspaces/{workspaceName}/proposals/{proposalName}/scriptReferences/{referenceName}", pathParameters),
		autorest.WithQueryParameters(queryParameters))
	return preparer.Prepare((&http.Request{}).WithContext(ctx))
}

// GetSender sends the Get request. The method will close the
// http.Response Body if it receives an error.
func (client ScriptReferencesClient) GetSender(req *http.Request) (*http.Response, error) {
	return client.Send(req, azure.DoRetryWithRegistration(client.Client))
}

// GetResponder handles the response to the Get request. The method always
// closes the http.Response Body.
func (client ScriptReferencesClient) GetResponder(resp *http.Response) (result ScriptReference, err error) {
	err = autorest.Respond(
		resp,
		azure.WithErrorUnlessStatusCode(http.StatusOK),
		autorest.ByUnmarshallingJSON(&result),
		autorest.ByClosing())
	result.Response = autorest.Response{Response: resp}
	return
}

// ListByProposal list ScriptReference in a Proposal
// Parameters:
// resourceGroupName - the resource group name.
// workspaceName - the name of the workspace.
// proposalName - the name of the proposal.
// skipToken - continuation token
func (client ScriptReferencesClient) ListByProposal(ctx context.Context, resourceGroupName string, workspaceName string, proposalName string, skipToken string) (result ScriptReferenceListPage, err error) {
	if tracing.IsEnabled() {
		ctx = tracing.StartSpan(ctx, fqdn+"/ScriptReferencesClient.ListByProposal")
		defer func() {
			sc := -1
			if result.srl.Response.Response != nil {
				sc = result.srl.Response.Response.StatusCode
			}
			tracing.EndSpan(ctx, sc, err)
		}()
	}
	result.fn = client.listByProposalNextResults
	req, err := client.ListByProposalPreparer(ctx, resourceGroupName, workspaceName, proposalName, skipToken)
	if err != nil {
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "ListByProposal", nil, "Failure preparing request")
		return
	}

	resp, err := client.ListByProposalSender(req)
	if err != nil {
		result.srl.Response = autorest.Response{Response: resp}
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "ListByProposal", resp, "Failure sending request")
		return
	}

	result.srl, err = client.ListByProposalResponder(resp)
	if err != nil {
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "ListByProposal", resp, "Failure responding to request")
	}
	if result.srl.hasNextLink() && result.srl.IsEmpty() {
		err = result.NextWithContext(ctx)
	}

	return
}

// ListByProposalPreparer prepares the ListByProposal request.
func (client ScriptReferencesClient) ListByProposalPreparer(ctx context.Context, resourceGroupName string, workspaceName string, proposalName string, skipToken string) (*http.Request, error) {
	pathParameters := map[string]interface{}{
		"proposalName":      autorest.Encode("path", proposalName),
		"resourceGroupName": autorest.Encode("path", resourceGroupName),
		"subscriptionId":    autorest.Encode("path", client.SubscriptionID),
		"workspaceName":     autorest.Encode("path", workspaceName),
	}

	const APIVersion = "2020-05-04-preview"
	queryParameters := map[string]interface{}{
		"api-version": APIVersion,
	}
	if len(skipToken) > 0 {
		queryParameters["$skipToken"] = autorest.Encode("query", skipToken)
	}

	preparer := autorest.CreatePreparer(
		autorest.AsGet(),
		autorest.WithBaseURL(client.BaseURI),
		autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataCollaboration/workspaces/{workspaceName}/proposals/{proposalName}/scriptReferences", pathParameters),
		autorest.WithQueryParameters(queryParameters))
	return preparer.Prepare((&http.Request{}).WithContext(ctx))
}

// ListByProposalSender sends the ListByProposal request. The method will close the
// http.Response Body if it receives an error.
func (client ScriptReferencesClient) ListByProposalSender(req *http.Request) (*http.Response, error) {
	return client.Send(req, azure.DoRetryWithRegistration(client.Client))
}

// ListByProposalResponder handles the response to the ListByProposal request. The method always
// closes the http.Response Body.
func (client ScriptReferencesClient) ListByProposalResponder(resp *http.Response) (result ScriptReferenceList, err error) {
	err = autorest.Respond(
		resp,
		azure.WithErrorUnlessStatusCode(http.StatusOK),
		autorest.ByUnmarshallingJSON(&result),
		autorest.ByClosing())
	result.Response = autorest.Response{Response: resp}
	return
}

// listByProposalNextResults retrieves the next set of results, if any.
func (client ScriptReferencesClient) listByProposalNextResults(ctx context.Context, lastResults ScriptReferenceList) (result ScriptReferenceList, err error) {
	req, err := lastResults.scriptReferenceListPreparer(ctx)
	if err != nil {
		return result, autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "listByProposalNextResults", nil, "Failure preparing next results request")
	}
	if req == nil {
		return
	}
	resp, err := client.ListByProposalSender(req)
	if err != nil {
		result.Response = autorest.Response{Response: resp}
		return result, autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "listByProposalNextResults", resp, "Failure sending next results request")
	}
	result, err = client.ListByProposalResponder(resp)
	if err != nil {
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "listByProposalNextResults", resp, "Failure responding to next results request")
	}
	return
}

// ListByProposalComplete enumerates all values, automatically crossing page boundaries as required.
func (client ScriptReferencesClient) ListByProposalComplete(ctx context.Context, resourceGroupName string, workspaceName string, proposalName string, skipToken string) (result ScriptReferenceListIterator, err error) {
	if tracing.IsEnabled() {
		ctx = tracing.StartSpan(ctx, fqdn+"/ScriptReferencesClient.ListByProposal")
		defer func() {
			sc := -1
			if result.Response().Response.Response != nil {
				sc = result.page.Response().Response.Response.StatusCode
			}
			tracing.EndSpan(ctx, sc, err)
		}()
	}
	result.page, err = client.ListByProposal(ctx, resourceGroupName, workspaceName, proposalName, skipToken)
	return
}

// Resolve resolve and return the Script that the ScriptReference points to
// Parameters:
// resourceGroupName - the resource group name.
// workspaceName - the name of the workspace.
// proposalName - the name of the proposal.
// referenceName - the name of the reference.
func (client ScriptReferencesClient) Resolve(ctx context.Context, resourceGroupName string, workspaceName string, proposalName string, referenceName string) (result ScriptModel, err error) {
	if tracing.IsEnabled() {
		ctx = tracing.StartSpan(ctx, fqdn+"/ScriptReferencesClient.Resolve")
		defer func() {
			sc := -1
			if result.Response.Response != nil {
				sc = result.Response.Response.StatusCode
			}
			tracing.EndSpan(ctx, sc, err)
		}()
	}
	req, err := client.ResolvePreparer(ctx, resourceGroupName, workspaceName, proposalName, referenceName)
	if err != nil {
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "Resolve", nil, "Failure preparing request")
		return
	}

	resp, err := client.ResolveSender(req)
	if err != nil {
		result.Response = autorest.Response{Response: resp}
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "Resolve", resp, "Failure sending request")
		return
	}

	result, err = client.ResolveResponder(resp)
	if err != nil {
		err = autorest.NewErrorWithError(err, "datacollaboration.ScriptReferencesClient", "Resolve", resp, "Failure responding to request")
	}

	return
}

// ResolvePreparer prepares the Resolve request.
func (client ScriptReferencesClient) ResolvePreparer(ctx context.Context, resourceGroupName string, workspaceName string, proposalName string, referenceName string) (*http.Request, error) {
	pathParameters := map[string]interface{}{
		"proposalName":      autorest.Encode("path", proposalName),
		"referenceName":     autorest.Encode("path", referenceName),
		"resourceGroupName": autorest.Encode("path", resourceGroupName),
		"subscriptionId":    autorest.Encode("path", client.SubscriptionID),
		"workspaceName":     autorest.Encode("path", workspaceName),
	}

	const APIVersion = "2020-05-04-preview"
	queryParameters := map[string]interface{}{
		"api-version": APIVersion,
	}

	preparer := autorest.CreatePreparer(
		autorest.AsPost(),
		autorest.WithBaseURL(client.BaseURI),
		autorest.WithPathParameters("/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataCollaboration/workspaces/{workspaceName}/proposals/{proposalName}/scriptReferences/{referenceName}/resolve", pathParameters),
		autorest.WithQueryParameters(queryParameters))
	return preparer.Prepare((&http.Request{}).WithContext(ctx))
}

// ResolveSender sends the Resolve request. The method will close the
// http.Response Body if it receives an error.
func (client ScriptReferencesClient) ResolveSender(req *http.Request) (*http.Response, error) {
	return client.Send(req, azure.DoRetryWithRegistration(client.Client))
}

// ResolveResponder handles the response to the Resolve request. The method always
// closes the http.Response Body.
func (client ScriptReferencesClient) ResolveResponder(resp *http.Response) (result ScriptModel, err error) {
	err = autorest.Respond(
		resp,
		azure.WithErrorUnlessStatusCode(http.StatusOK),
		autorest.ByUnmarshallingJSON(&result),
		autorest.ByClosing())
	result.Response = autorest.Response{Response: resp}
	return
}
